//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UsuarioProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioProxy.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Add", ReplyAction="http://tempuri.org/IUsuarioService/AddResponse")]
        bool Add(Model.UsuarioModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Update", ReplyAction="http://tempuri.org/IUsuarioService/UpdateResponse")]
        bool Update(Model.UsuarioModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Delete", ReplyAction="http://tempuri.org/IUsuarioService/DeleteResponse")]
        bool Delete(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/List", ReplyAction="http://tempuri.org/IUsuarioService/ListResponse")]
        Model.UsuarioModel[] List(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/Find", ReplyAction="http://tempuri.org/IUsuarioService/FindResponse")]
        Model.UsuarioModel[] Find(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : Web.UsuarioProxy.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<Web.UsuarioProxy.IUsuarioService>, Web.UsuarioProxy.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(Model.UsuarioModel data) {
            return base.Channel.Add(data);
        }
        
        public bool Update(Model.UsuarioModel data) {
            return base.Channel.Update(data);
        }
        
        public bool Delete(int codigo) {
            return base.Channel.Delete(codigo);
        }
        
        public Model.UsuarioModel[] List(int codigo) {
            return base.Channel.List(codigo);
        }
        
        public Model.UsuarioModel[] Find(string login) {
            return base.Channel.Find(login);
        }
    }
}
