//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.EstadoProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstadoProxy.IEstadoService")]
    public interface IEstadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoService/Add", ReplyAction="http://tempuri.org/IEstadoService/AddResponse")]
        bool Add(Model.EstadoModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoService/Update", ReplyAction="http://tempuri.org/IEstadoService/UpdateResponse")]
        bool Update(Model.EstadoModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoService/Delete", ReplyAction="http://tempuri.org/IEstadoService/DeleteResponse")]
        bool Delete(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstadoService/List", ReplyAction="http://tempuri.org/IEstadoService/ListResponse")]
        Model.EstadoModel[] List(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstadoServiceChannel : Web.EstadoProxy.IEstadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadoServiceClient : System.ServiceModel.ClientBase<Web.EstadoProxy.IEstadoService>, Web.EstadoProxy.IEstadoService {
        
        public EstadoServiceClient() {
        }
        
        public EstadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(Model.EstadoModel data) {
            return base.Channel.Add(data);
        }
        
        public bool Update(Model.EstadoModel data) {
            return base.Channel.Update(data);
        }
        
        public bool Delete(int codigo) {
            return base.Channel.Delete(codigo);
        }
        
        public Model.EstadoModel[] List(int codigo) {
            return base.Channel.List(codigo);
        }
    }
}
