//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.CidadeProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CidadeProxy.ICidadeService")]
    public interface ICidadeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeService/Add", ReplyAction="http://tempuri.org/ICidadeService/AddResponse")]
        bool Add(Model.CidadeModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeService/Update", ReplyAction="http://tempuri.org/ICidadeService/UpdateResponse")]
        bool Update(Model.CidadeModel data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeService/Delete", ReplyAction="http://tempuri.org/ICidadeService/DeleteResponse")]
        bool Delete(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidadeService/List", ReplyAction="http://tempuri.org/ICidadeService/ListResponse")]
        Model.CidadeModel[] List(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICidadeServiceChannel : Web.CidadeProxy.ICidadeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CidadeServiceClient : System.ServiceModel.ClientBase<Web.CidadeProxy.ICidadeService>, Web.CidadeProxy.ICidadeService {
        
        public CidadeServiceClient() {
        }
        
        public CidadeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CidadeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(Model.CidadeModel data) {
            return base.Channel.Add(data);
        }
        
        public bool Update(Model.CidadeModel data) {
            return base.Channel.Update(data);
        }
        
        public bool Delete(int codigo) {
            return base.Channel.Delete(codigo);
        }
        
        public Model.CidadeModel[] List(int codigo) {
            return base.Channel.List(codigo);
        }
    }
}
